<a href="<?= $this->url(array(
                                 'controller' => 'Login',
                                 'action' 	  => 'index'
								 
                                 )); ?>">Login</a><br />
								 
<a href="<?= $this->url(array(
                                 'controller' => 'Login',
                                 'action' 	  => 'welcome'
								 
                                 )); ?>">Home</a><br />						

<h1>Registration Form</h1>
<?php
echo $this->form;
?>